### ISSUE TITLE
Bug: OHv3 Holds VFATs in hard reset in FW v3.0.8.a?

### ISSUE THREAD

**Issue by bdorney** [cms-gem-daq-project/OptoHybridv3#7] opened 2018-02-09 14:57 UTC
See: http://cmsonline.cern.ch/cms-elog/1028225

Based on study with chip scope @evka85 and I believe that the VFATs are being held in hard reset by the OH.

@andrewpeck

**Comment by bdorney** [comment] 2018-02-09 17:51
I was able to roll the FW back to the last stable version I have tested: v3.0.4.A

Here the VFATs behave normally (updated the above e-log post to reflect show the tests performed).

**Comment by evka85** [comment] 2018-02-11 04:09
Actually the problem was very strange -- looking at the VFAT links on CTP7 I saw that all VFATs were transmitting normal idle words, but periodically they would transmit 0x00, which is not a valid word except when transmitting a DAQ packet (which was not the case). Also they would not respond to SYNC commands. You can see a chipscope picture of one VFAT attached.
To make matters worse, this was not happening on VFAT #13 at all, and it was happening at a lower rate on VFAT #14 (this one did have a chance to respond to SYNC and SYNC_CHECK commands most of the time).

We did multiple power cycles of the OH, and also tried power-cycling and reprogramming CTP7 and even AMC13, but that didn't change anything.

So it seems that this could only be caused by VFAT reset.. And it did get fixed with an OH firmware rollback...
![screenshot from 2018-02-09 15 30 57](https://user-images.githubusercontent.com/8192542/36069430-c03d0854-0ee9-11e8-82bf-771f9063106b.png)

**Comment by andrewpeck** [comment] 2018-02-12 21:39
Fixed in 3.0.9.A

**Closed** 2018-02-12 21:42 UTC
